/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BEU.Casa;
import BEU.Cliente;
import BEU.Propiedad;
import BLL.GestionCasa;
import BLL.GestionCliente;
import BLL.GestionPropiedad;
import Castillo.Util;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author windows
 */
public class frmVentaDeCasas extends javax.swing.JInternalFrame {

    private String titulo = "";
    private GestionCasa casaBll = new GestionCasa();
    private GestionCliente clienteBll = new GestionCliente();
    private GestionPropiedad propiedadBll = new GestionPropiedad();
    private List<Casa> casas;
    private List<Cliente> clientes;
    private List<Propiedad> propiedades;

    private boolean validar() {
        Casa cs = (Casa) this.cbxNumCasa.getSelectedItem();
        Cliente cl = (Cliente) this.cbxCliente.getSelectedItem();
        if (cl.getNombre().equals("-Seleccione--")) {
            VTNPrincipal.verMensaje("Cliente no Válido", JOptionPane.WARNING_MESSAGE, titulo);
            return false;
        }
        if (cs.getNumero().equals("--Seleccione--")) {
            VTNPrincipal.verMensaje("Casa no Válido", JOptionPane.WARNING_MESSAGE, titulo);
            return false;
        }
        return true;

    }

    private void consultarCasa() throws IOException {
        Casa cs = (Casa) this.cbxNumCasa.getSelectedItem();
        propiedades = propiedadBll.reportar(cs.getNumero());
        this.txtDescripcion.setText(propiedadBll.imprimir());
    }

    
    private void leerClientes() {
        try {
            Cliente ficticia = new Cliente();
            ficticia.setNombre("--Seleccione--");
            ficticia.setApellido("");
            this.cbxCliente.addItem(ficticia);
            clientes = clienteBll.getClientes();
            clientes.forEach((c) -> {
                this.cbxCliente.addItem(c);
            });

        } catch (Exception e) {
            Util.imprimir("Error¡¡" + e.toString());
            VTNPrincipal.verMensaje("Error al leer los Clientes", JOptionPane.ERROR_MESSAGE, titulo);
        }
    }

    private void leerCasas() {
        try {
            Casa ficticia = new Casa();
            ficticia.setNumero("--Seleccione--");
            ficticia.setDescripcion("");
            this.cbxNumCasa.addItem(ficticia);
            casas = casaBll.getCasas();
            casas.forEach((c) -> {
                this.cbxNumCasa.addItem(c);
            });

        } catch (Exception e) {
            Util.imprimir("Error¡¡" + e.toString());
            VTNPrincipal.verMensaje("Error al leer las Casas", JOptionPane.ERROR_MESSAGE, titulo);
        }
    }

    private void crearPropiedad() throws IOException {
        Casa cs = (Casa) this.cbxNumCasa.getSelectedItem();
        Cliente cl = (Cliente) this.cbxCliente.getSelectedItem();
        propiedadBll.crear();
        propiedadBll.configurar(cl, cs);
        propiedadBll.archivar();
    }

    /**
     * Creates new form frmVentaDeCasaS
     */
    public frmVentaDeCasas() {
        initComponents();
        leerClientes();
        leerCasas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCliente = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        cbxCliente = new javax.swing.JComboBox<>();
        lblVentaCasas = new javax.swing.JLabel();
        pnlCasa = new javax.swing.JPanel();
        lblNumCasa = new javax.swing.JLabel();
        cbxNumCasa = new javax.swing.JComboBox<>();
        pnlDescripcion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblCredito = new javax.swing.JLabel();
        spnMonto = new javax.swing.JSpinner();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Venta");

        pnlCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(2, 2, 2))); // NOI18N

        lblCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCliente.setText("Nombre:");

        cbxCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        lblVentaCasas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblVentaCasas.setForeground(new java.awt.Color(204, 0, 0));
        lblVentaCasas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentaCasas.setText("Venta de Casas");

        pnlCasa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Casa"));

        lblNumCasa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumCasa.setText("N°:");

        cbxNumCasa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        pnlDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Descripción"));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        javax.swing.GroupLayout pnlDescripcionLayout = new javax.swing.GroupLayout(pnlDescripcion);
        pnlDescripcion.setLayout(pnlDescripcionLayout);
        pnlDescripcionLayout.setHorizontalGroup(
            pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDescripcionLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlDescripcionLayout.setVerticalGroup(
            pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblCredito.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCredito.setText("Monto:");

        spnMonto.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 100.0f));

        btnGuardar.setBackground(new java.awt.Color(102, 0, 102));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(153, 0, 0));
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCasaLayout = new javax.swing.GroupLayout(pnlCasa);
        pnlCasa.setLayout(pnlCasaLayout);
        pnlCasaLayout.setHorizontalGroup(
            pnlCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCasaLayout.createSequentialGroup()
                .addGroup(pnlCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCasaLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblCredito)
                        .addGap(27, 27, 27)
                        .addComponent(spnMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar))
                    .addGroup(pnlCasaLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(pnlCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCasaLayout.createSequentialGroup()
                                .addComponent(lblNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar))
                            .addComponent(pnlDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnlCasaLayout.setVerticalGroup(
            pnlCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCasaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumCasa)
                    .addComponent(cbxNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(pnlDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCasaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCasaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lblVentaCasas, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlCasa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVentaCasas)
                .addGap(18, 18, 18)
                .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
             if(this.validar()){
                 this.crearPropiedad();
                VTNPrincipal.verMensaje("Propiedad registrada Correctamente ", JOptionPane.INFORMATION_MESSAGE, titulo);
            }
        } catch (Exception e) {
            Util.imprimir("Error:¡!" + e.toString());
            VTNPrincipal.verMensaje("Error al Crear la Propiedad", JOptionPane.ERROR_MESSAGE, titulo);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            this.consultarCasa();
            VTNPrincipal.verMensaje("Búsqueda realizada con éxito", WIDTH, titulo);

        } catch (Exception e) {
            Util.imprimir("Error:¡!" + e.toString());
            VTNPrincipal.verMensaje("Error al buscar la Casa", JOptionPane.ERROR_MESSAGE, titulo);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Cliente> cbxCliente;
    private javax.swing.JComboBox<Casa> cbxNumCasa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCredito;
    private javax.swing.JLabel lblNumCasa;
    private javax.swing.JLabel lblVentaCasas;
    private javax.swing.JPanel pnlCasa;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlDescripcion;
    private javax.swing.JSpinner spnMonto;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
